### ISSUE TITLE
Give more information about inference.

### ISSUE THREAD

**Issue by CGod1991** [junting/seg2vid#1]
Could you give more information about inference?  There are three pretrained models:refine_genmask_098000.pth.tar、refine_genmask_w_mask_098000.pth.tar and refine_genmask_w_mask_two_path_096000.pth.tar, but i don't know which one i should use.

**Comment by junting** [comment]
Hi, 
Sorry for the misleading, we have already updated the model's name with their corresponding setting.
Thanks,
